Vagrant.configure("2") do |config|
  config.vm.box = "paulovn/spark-base64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6012"
    vb.cpus = 4
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080  # Port Spark UI
  config.vm.network "forwarded_port", guest: 7077, host: 7077  # Port Spark master
  config.vm.network "forwarded_port", guest: 5000, host: 5000  # Port Flask

  config.vm.synced_folder "./data", "/vagrant_data"

  config.vm.provision "shell", inline: <<-SHELL
    sudo su
    sudo apt-get update
    sudo apt-get install -y openjdk-8-jdk wget python3-pip screen

    wget https://downloads.apache.org/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz
    tar -xzf spark-3.5.1-bin-hadoop3.tgz
    sudo mv spark-3.5.1-bin-hadoop3 /usr/local/spark
    echo 'export SPARK_HOME=/usr/local/spark' >> ~/.bashrc
    echo 'export PATH=$PATH:$SPARK_HOME/bin' >> ~/.bashrc
    source ~/.bashrc

    pip3 install flask
    pip install flask

    curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.13.1-amd64.deb
    sudo dpkg -i filebeat-7.13.1-amd64.deb

    sudo wget -O get-docker.sh https://get.docker.com/
    sudo sh get-docker.sh

    # chmod +x /vagrant_data/start_spark.sh
    # screen -dmS spark /vagrant_data/start_spark.sh
  SHELL
end
